spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    password: my_db
    url: jdbc:mysql://localhost:3306/my_db
    username: my_db
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
info:
  app:
    description: This is auth service on spring boot application
    name: Auth Service
    version: 1.0.0
