server:
  port: 8082
spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: springboot
    password: springboot
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
info:
  app:
    description: Customer Service on spring boot application
    name: Customer Service Application
    version: 1.0.0